# Generated by Django 4.2.4 on 2023-08-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
