# Generated by Django 4.2.4 on 2023-08-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_paper_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
